name: GitHub Actions Demo
on:
  push: 
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  jobs: 
    Build: 
       runs-on: ubuntu-latest
       steps:
          - run: |
             echo "Job trigerred by: ${{ github.event_name }}"
             echo "Name of the branch: ${{ guthib.ref }} , and repository is ."
          - uses: actions/checkout@v3.3.0

          - name: List all files in the repo
            run: |
              echo "The Repo ${{ githuv.repository }} contains the folowwing tree."
          
    
